#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#include <driver/gpio.h>

#define SECUREVITALS_I2C_SDA_PIN GPIO_NUM_21
#define SECUREVITALS_I2C_SCL_PIN GPIO_NUM_22
#define SECUREVITALS_I2C_CLOCK_HZ 400000U

#define SECUREVITALS_MAX30102_INT_PIN GPIO_NUM_19
#define SECUREVITALS_PULSE_OX_SAMPLE_RATE_HZ 100U
#define SECUREVITALS_PULSE_OX_POLL_PERIOD_MS 50U
#define SECUREVITALS_PULSE_OX_LOG_PERIOD_MS 1000U

#endif // PROJECT_CONFIG_H
